name: Accessibility Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: false
        type: string
      repository:
        description: 'Repository (owner/repo)'
        required: false
        type: string
      branch:
        description: 'Branch to analyze'
        required: false
        type: string
        default: 'main'

jobs:
  accessibility-check:
    name: 🔍 Accessibility Review
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: 🔄 Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for accurate diff analysis
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: 🔧 Install dependencies
        run: |
          echo "Installing A11y-MCP dependencies..."
          npm install --production
          
          echo "Installing additional GitHub API dependencies..."
          npm install @octokit/rest

      - name: 📁 Check for configuration
        id: config-check
        run: |
          if [ -f ".a11y/config.json" ]; then
            echo "config_exists=true" >> $GITHUB_OUTPUT
            echo "✅ Found .a11y/config.json"
            cat .a11y/config.json
          else
            echo "config_exists=false" >> $GITHUB_OUTPUT
            echo "⚠️ No .a11y/config.json found. Using default configuration."
          fi

      - name: 🔧 Setup A11y Configuration
        if: steps.config-check.outputs.config_exists == 'false'
        run: |
          echo "📝 Creating default accessibility configuration..."
          mkdir -p .a11y
          cat > .a11y/config.json << 'EOF'
          {
            "$schema": "https://a11y-mcp.internal/schema/v1",
            "wcagLevel": "AA",
            "wcagVersion": "2.2",
            "strictMode": true,
            "ldsEnforcement": {
              "enabled": true,
              "storybookUrl": "https://storybook.lilly.internal",
              "requireApprovedComponents": true,
              "allowedExceptions": ["src/legacy/**"],
              "cacheComponents": true,
              "cacheTTL": 3600
            },
            "rules": {
              "aria-required": {
                "enabled": true,
                "severity": "error"
              },
              "keyboard-nav": {
                "enabled": true,
                "severity": "error"
              },
              "semantic-html": {
                "enabled": true,
                "severity": "error"
              },
              "alt-text": {
                "enabled": true,
                "severity": "error"
              },
              "lds-components": {
                "enabled": true,
                "severity": "warning"
              }
            },
            "excludedRules": ["color-contrast"],
            "failureThresholds": {
              "error": 0,
              "warning": 10
            },
            "ignore": [
              "**/*.test.{js,jsx,ts,tsx}",
              "**/*.stories.{js,jsx,ts,tsx}",
              "node_modules/**",
              "dist/**",
              "build/**",
              ".git/**"
            ]
          }
          EOF
          echo "✅ Default configuration created"

      - name: 📊 Get PR Information
        id: pr-info
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
            echo "repository=${{ github.repository }}" >> $GITHUB_OUTPUT
            echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
            echo "base_branch=${{ github.event.pull_request.base.ref }}" >> $GITHUB_OUTPUT
            echo "is_pr=true" >> $GITHUB_OUTPUT
            echo "📋 PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
          else
            echo "pr_number=${{ github.event.inputs.pr_number || 'manual' }}" >> $GITHUB_OUTPUT
            echo "repository=${{ github.repository }}" >> $GITHUB_OUTPUT
            echo "branch=${{ github.event.inputs.branch || 'main' }}" >> $GITHUB_OUTPUT
            echo "base_branch=main" >> $GITHUB_OUTPUT
            echo "is_pr=false" >> $GITHUB_OUTPUT
            echo "📊 Manual analysis for ${{ github.event.inputs.branch || 'main' }}"
          fi

      - name: 🔍 Run Accessibility Analysis
        id: a11y-analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ steps.pr-info.outputs.pr_number }}
          REPOSITORY: ${{ steps.pr-info.outputs.repository }}
          BRANCH: ${{ steps.pr-info.outputs.branch }}
        run: |
          echo "🚀 Starting accessibility analysis..."
          
          # Create analysis script
          cat > analyze-pr.js << 'EOF'
          const { Octokit } = require('@octokit/rest');
          const { spawn } = require('child_process');
          const fs = require('fs');
          const path = require('path');

          // Initialize GitHub API client
          const octokit = new Octokit({
            auth: process.env.GITHUB_TOKEN
          });

          async function analyzePR() {
            try {
              const [owner, repo] = process.env.REPOSITORY.split('/');
              const prNumber = parseInt(process.env.PR_NUMBER);
              
              console.log(`📋 Analyzing PR #${prNumber} in ${owner}/${repo}`);
              
              // Get PR details
              const { data: pr } = await octokit.rest.pulls.get({
                owner,
                repo,
                pull_number: prNumber
              });
              
              console.log(`📊 PR Title: ${pr.title}`);
              console.log(`🌿 Branch: ${pr.head.ref}`);
              
              // Get changed files
              const { data: files } = await octokit.rest.pulls.listFiles({
                owner,
                repo,
                pull_number: prNumber,
                per_page: 100
              });
              
              console.log(`📄 Found ${files.length} changed files`);
              
              // Filter relevant files
              const relevantFiles = files.filter(file => {
                const ext = path.extname(file.filename);
                return ['.tsx', '.jsx', '.ts', '.js', '.css', '.scss'].includes(ext) &&
                       !file.filename.includes('test.') &&
                       !file.filename.includes('stories.') &&
                       file.status !== 'removed';
              });
              
              console.log(`🎯 ${relevantFiles.length} files relevant for accessibility analysis`);
              
              // Analyze files
              const violations = [];
              
              for (const file of relevantFiles) {
                try {
                  // Get file content at the PR branch
                  const { data: content } = await octokit.rest.repos.getContent({
                    owner,
                    repo,
                    path: file.filename,
                    ref: pr.head.sha
                  });
                  
                  if ('content' in content) {
                    const decodedContent = Buffer.from(content.content, 'base64').toString('utf-8');
                    
                    // Run accessibility check
                    const violation = await checkAccessibility(file.filename, decodedContent);
                    if (violation) {
                      violations.push({ ...violation, file: file.filename });
                    }
                  }
                } catch (error) {
                  console.warn(`Failed to analyze ${file.filename}:`, error.message);
                }
              }
              
              // Generate results
              const results = {
                prNumber,
                repository: `${owner}/${repo}`,
                branch: pr.head.ref,
                totalFiles: files.length,
                analyzedFiles: relevantFiles.length,
                violations,
                summary: {
                  totalViolations: violations.length,
                  errors: violations.filter(v => v.severity === 'error').length,
                  warnings: violations.filter(v => v.severity === 'warning').length,
                  info: violations.filter(v => v.severity === 'info').length
                },
                timestamp: new Date().toISOString()
              };
              
              // Save results
              fs.writeFileSync('a11y-results.json', JSON.stringify(results, null, 2));
              
              console.log(`✅ Analysis complete: ${violations.length} violations found`);
              return results;
              
            } catch (error) {
              console.error('❌ Analysis failed:', error);
              process.exit(1);
            }
          }
          
          async function checkAccessibility(filename, content) {
            // Simple rule checking
            const violations = [];
            
            // Check for images without alt attributes
            if (filename.match(/\.(jsx|tsx)$/)) {
              const imgMatches = content.match(/<img[^>]*>/g) || [];
              for (const img of imgMatches) {
                if (!img.includes('alt=')) {
                  violations.push({
                    id: 'img-missing-alt',
                    severity: 'error',
                    title: 'Image missing alt attribute',
                    description: 'Image element is missing required alt attribute for accessibility',
                    line: content.substring(0, content.indexOf(img)).split('\n').length + 1,
                    wcagCriteria: ['1.1.1'],
                    fixSuggestion: 'Add alt attribute: <img src="..." alt="Description of image">'
                  });
                }
              }
              
              // Check for div with onClick (non-semantic button)
              if (content.includes('onClick')) {
                const divClickMatches = content.match(/<div[^>]*onClick/g) || [];
                for (const div of divClickMatches) {
                  violations.push({
                    id: 'div-button',
                    severity: 'error',
                    title: 'Non-semantic interactive element',
                    description: 'Div with onClick should be replaced with semantic button element',
                    line: content.substring(0, content.indexOf(div)).split('\n').length + 1,
                    wcagCriteria: ['1.3.1'],
                    fixSuggestion: 'Use <button onClick={handler}> instead of <div onClick={handler}>'
                  });
                }
              }
              
              // Check for buttons without accessible names
              const buttonMatches = content.match(/<button[^>]*>/g) || [];
              for (const button of buttonMatches) {
                if (!button.includes('aria-label') && !button.includes('children')) {
                  violations.push({
                    id: 'button-missing-label',
                    severity: 'error',
                    title: 'Button missing accessible name',
                    description: 'Button element needs aria-label or children for accessibility',
                    line: content.substring(0, content.indexOf(button)).split('\n').length + 1,
                    wcagCriteria: ['4.1.2'],
                    fixSuggestion: 'Add aria-label or ensure button has text content'
                  });
                }
              }
            }
            
            // Check for CSS focus styles
            if (filename.match(/\.(css|scss)$/)) {
              if (!content.includes(':focus')) {
                violations.push({
                  id: 'missing-focus-styles',
                  severity: 'warning',
                  title: 'Missing focus styles',
                  description: 'CSS should include :focus styles for keyboard navigation',
                  line: 1,
                  wcagCriteria: ['2.4.7'],
                  fixSuggestion: 'Add :focus and :focus-visible styles for interactive elements'
                });
              }
            }
            
            return violations.length > 0 ? violations : null;
          }
          
          analyzePR();
          EOF
          
          # Run the analysis
          node analyze-pr.js
          
          # Check results
          if [ -f "a11y-results.json" ]; then
            echo "✅ Analysis completed successfully"
            VIOLATIONS=$(cat a11y-results.json | jq -r '.summary.totalViolations')
            ERRORS=$(cat a11y-results.json | jq -r '.summary.errors')
            WARNINGS=$(cat a11y-results.json | jq -r '.summary.warnings')
            
            echo "📊 Results: $VIOLATIONS total violations ($ERRORS errors, $WARNINGS warnings)"
            
            # Set output for next steps
            echo "violations=$VIOLATIONS" >> $GITHUB_OUTPUT
            echo "errors=$ERRORS" >> $GITHUB_OUTPUT
            echo "warnings=$WARNINGS" >> $GITHUB_OUTPUT
            
            if [ "$ERRORS" -gt 0 ]; then
              echo "❌ Found $ERRORS critical errors - build will fail"
              echo "has_errors=true" >> $GITHUB_OUTPUT
            else
              echo "✅ No critical errors found"
              echo "has_errors=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "❌ Analysis failed - no results file"
            echo "violations=0" >> $GITHUB_OUTPUT
            echo "errors=0" >> $GITHUB_OUTPUT
            echo "warnings=0" >> $GITHUB_OUTPUT
            echo "has_errors=false" >> $GITHUB_OUTPUT
          fi

      - name: 📋 Post PR Comment
        if: steps.a11y-analysis.outputs.violations > 0
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            // Read analysis results
            const results = JSON.parse(fs.readFileSync('a11y-results.json', 'utf8'));
            
            // Create comment body
            let comment = `## 🔍 Accessibility Review Results\n\n`;
            comment += `**Found ${results.summary.totalViolations} accessibility violation(s):**\n\n`;
            
            if (results.summary.errors > 0) {
              comment += `### 🔴 Critical Errors (Must Fix)\n\n`;
              const errors = results.violations.filter(v => v.severity === 'error');
              errors.forEach(v => {
                comment += `- **${v.title}** in \`${v.file}\`: ${v.description}\n`;
                comment += `  - WCAG: ${v.wcagCriteria.join(', ')}\n`;
                comment += `  - Fix: ${v.fixSuggestion}\n\n`;
              });
            }
            
            if (results.summary.warnings > 0) {
              comment += `### 🟡 Warnings (Recommended)\n\n`;
              const warnings = results.violations.filter(v => v.severity === 'warning');
              warnings.forEach(v => {
                comment += `- **${v.title}** in \`${v.file}\`: ${v.description}\n`;
                comment += `  - Fix: ${v.fixSuggestion}\n\n`;
              });
            }
            
            comment += `### 📊 Summary\n\n`;
            comment += `- **Files Analyzed**: ${results.analyzedFiles}\n`;
            comment += `- **Total Violations**: ${results.summary.totalViolations}\n`;
            comment += `- **Critical Errors**: ${results.summary.errors}\n`;
            comment += `- **Warnings**: ${results.summary.warnings}\n\n`;
            
            comment += `### 📚 Resources\n\n`;
            comment += `- [WCAG 2.2 Guidelines](https://www.w3.org/WAI/WCAG22/quickref/)\n`;
            comment += `- [LDS Storybook](https://storybook.lilly.internal)\n`;
            comment += `- [Accessibility Testing Tools](https://github.com/dequelabs/axe-core)\n\n`;
            
            comment += `---\n`;
            comment += `*Analysis performed by A11y-MCP Server*\n`;
            
            // Post comment to PR
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
            
            console.log('✅ Posted accessibility results to PR');

      - name: 🎯 Success Summary
        if: steps.a11y-analysis.outputs.has_errors == 'false'
        run: |
          echo "✅ Accessibility check completed successfully!"
          echo "📊 No critical errors found"
          echo "🔍 Analyzed ${{ steps.a11y-analysis.outputs.analyzedFiles }} files"
          echo "⚠️  ${{ steps.a11y-analysis.outputs.warnings }} warnings (non-blocking)"
          
          # Create summary artifact
          echo "## Accessibility Analysis Summary" > accessibility-summary.md
          echo "" >> accessibility-summary.md
          echo "**Status**: ✅ Passed" >> accessibility-summary.md
          echo "**Files Analyzed**: ${{ steps.a11y-analysis.outputs.analyzedFiles }}" >> accessibility-summary.md
          echo "**Violations Found**: ${{ steps.a11y-analysis.outputs.violations }}" >> accessibility-summary.md
          echo "**Critical Errors**: ${{ steps.a11y-analysis.outputs.errors }}" >> accessibility-summary.md
          echo "**Warnings**: ${{ steps.a11y-analysis.outputs.warnings }}" >> accessibility-summary.md
          echo "" >> accessibility-summary.md
          echo "This PR meets WCAG 2.2 AA accessibility standards." >> accessibility-summary.md

      - name: 📦 Upload Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: accessibility-analysis-results
          path: |
            a11y-results.json
            accessibility-summary.md
          retention-days: 30

      - name: ❌ Fail on Critical Errors
        if: steps.a11y-analysis.outputs.has_errors == 'true'
        run: |
          echo "❌ Accessibility check failed due to ${{ steps.a11y-analysis.outputs.errors }} critical error(s)"
          echo "🔧 Please fix the critical accessibility violations before merging"
          echo ""
          echo "Errors found:"
          cat a11y-results.json | jq -r '.violations[] | select(.severity == "error") | "- \(.title) in \(.file)"'
          exit 1