name: Accessibility Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: false
        type: string
      repository:
        description: 'Repository (owner/repo)'
        required: false
        type: string
      branch:
        description: 'Branch to analyze'
        required: false
        type: string
        default: 'main'

jobs:
  accessibility-check:
    name: 🔍 Accessibility Review
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: 🔄 Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for accurate diff analysis
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: 🔧 Install dependencies
        run: |
          echo "Installing A11y-MCP dependencies..."
          npm install
          
          echo "✅ Dependencies installed"
          echo "📦 MCP SDK version:"
          npm list @modelcontextprotocol/sdk || echo "⚠️  MCP SDK not found"
          echo "📦 Octokit version:"
          npm list @octokit/rest || echo "⚠️  Octokit not found"

      - name: 📁 Check for configuration
        id: config-check
        run: |
          if [ -f ".a11y/config.json" ]; then
            echo "config_exists=true" >> $GITHUB_OUTPUT
            echo "✅ Found .a11y/config.json"
            cat .a11y/config.json
          else
            echo "config_exists=false" >> $GITHUB_OUTPUT
            echo "⚠️ No .a11y/config.json found. Using default configuration."
          fi

      - name: 🔧 Setup A11y Configuration
        if: steps.config-check.outputs.config_exists == 'false'
        run: |
          echo "📝 Creating default accessibility configuration..."
          mkdir -p .a11y
          cat > .a11y/config.json << 'EOF'
          {
            "$schema": "https://a11y-mcp.internal/schema/v1",
            "wcagLevel": "AA",
            "wcagVersion": "2.2",
            "strictMode": true,
            "ldsEnforcement": {
              "enabled": true,
              "storybookUrl": "https://storybook.lilly.internal",
              "requireApprovedComponents": true,
              "allowedExceptions": ["src/legacy/**"],
              "cacheComponents": true,
              "cacheTTL": 3600
            },
            "rules": {
              "aria-required": {
                "enabled": true,
                "severity": "error"
              },
              "keyboard-nav": {
                "enabled": true,
                "severity": "error"
              },
              "semantic-html": {
                "enabled": true,
                "severity": "error"
              },
              "alt-text": {
                "enabled": true,
                "severity": "error"
              },
              "lds-components": {
                "enabled": true,
                "severity": "warning"
              }
            },
            "excludedRules": ["color-contrast"],
            "failureThresholds": {
              "error": 0,
              "warning": 10
            },
            "ignore": [
              "**/*.test.{js,jsx,ts,tsx}",
              "**/*.stories.{js,jsx,ts,tsx}",
              "node_modules/**",
              "dist/**",
              "build/**",
              ".git/**"
            ]
          }
          EOF
          echo "✅ Default configuration created"

      - name: 📊 Get PR Information
        id: pr-info
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
            echo "repository=${{ github.repository }}" >> $GITHUB_OUTPUT
            echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
            echo "base_branch=${{ github.event.pull_request.base.ref }}" >> $GITHUB_OUTPUT
            echo "is_pr=true" >> $GITHUB_OUTPUT
            echo "📋 PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
          else
            echo "pr_number=${{ github.event.inputs.pr_number || 'manual' }}" >> $GITHUB_OUTPUT
            echo "repository=${{ github.repository }}" >> $GITHUB_OUTPUT
            echo "branch=${{ github.event.inputs.branch || 'main' }}" >> $GITHUB_OUTPUT
            echo "base_branch=main" >> $GITHUB_OUTPUT
            echo "is_pr=false" >> $GITHUB_OUTPUT
            echo "📊 Manual analysis for ${{ github.event.inputs.branch || 'main' }}"
          fi

      - name: 🔍 Run Accessibility Analysis via MCP
        id: a11y-analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ steps.pr-info.outputs.pr_number }}
          REPOSITORY: ${{ steps.pr-info.outputs.repository }}
          BRANCH: ${{ steps.pr-info.outputs.branch }}
        run: |
          echo "🚀 Starting accessibility analysis via MCP server..."
          
          # Test MCP server connection first
          echo "🔌 Testing MCP server connection..."
          node scripts/mcp-client.js test || {
            echo "❌ MCP server test failed. Checking if server exists..."
            if [ ! -f "src/mcp-server.js" ]; then
              echo "❌ MCP server not found. Please ensure src/mcp-server.js exists."
              exit 1
            fi
            echo "⚠️  MCP server exists but test failed. Continuing anyway..."
          }
          
          # Run the hybrid analysis (production-ready)
          echo "📊 Running PR analysis with hybrid analyzer (production)..."
          node scripts/analyze-pr-mcp.js
          
          # Check results
          if [ -f "a11y-results.json" ]; then
            echo "✅ Analysis completed successfully"
            VIOLATIONS=$(cat a11y-results.json | jq -r '.summary.totalViolations // 0')
            ERRORS=$(cat a11y-results.json | jq -r '.summary.errors // 0')
            WARNINGS=$(cat a11y-results.json | jq -r '.summary.warnings // 0')
            ANALYZED=$(cat a11y-results.json | jq -r '.analyzedFiles // 0')
            
            echo "📊 Results: $VIOLATIONS total violations ($ERRORS errors, $WARNINGS warnings)"
            echo "📁 Files analyzed: $ANALYZED"
            
            # Set output for next steps
            echo "violations=$VIOLATIONS" >> $GITHUB_OUTPUT
            echo "errors=$ERRORS" >> $GITHUB_OUTPUT
            echo "warnings=$WARNINGS" >> $GITHUB_OUTPUT
            echo "analyzedFiles=$ANALYZED" >> $GITHUB_OUTPUT
            
            if [ "$ERRORS" -gt 0 ]; then
              echo "❌ Found $ERRORS critical errors - build will fail"
              echo "has_errors=true" >> $GITHUB_OUTPUT
            else
              echo "✅ No critical errors found"
              echo "has_errors=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "❌ Analysis failed - no results file generated"
            echo "⚠️  This might indicate an MCP server communication issue"
            echo "violations=0" >> $GITHUB_OUTPUT
            echo "errors=0" >> $GITHUB_OUTPUT
            echo "warnings=0" >> $GITHUB_OUTPUT
            echo "analyzedFiles=0" >> $GITHUB_OUTPUT
            echo "has_errors=false" >> $GITHUB_OUTPUT
          fi

      - name: 📋 Post PR Comment
        if: always() && steps.a11y-analysis.outputs.violations != null
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            // Read analysis results
            if (!fs.existsSync('a11y-results.json')) {
              console.log('⚠️  No results file found. Skipping comment.');
              return;
            }
            
            const results = JSON.parse(fs.readFileSync('a11y-results.json', 'utf8'));
            
            // Create comment body
            let comment = `## 🔍 Accessibility Review Results (via MCP)\n\n`;
            
            if (results.summary.totalViolations === 0) {
              comment += `✅ **No accessibility violations found!**\n\n`;
              comment += `- **Files Analyzed**: ${results.analyzedFiles}\n`;
              comment += `- **Status**: All checks passed\n\n`;
              comment += `This PR meets WCAG 2.2 AA accessibility standards. 🎉\n\n`;
            } else {
              comment += `**Found ${results.summary.totalViolations} accessibility violation(s):**\n\n`;
              
              // Group violations by file
              const violationsByFile = {};
              results.violations.forEach(v => {
                if (!violationsByFile[v.file]) {
                  violationsByFile[v.file] = [];
                }
                violationsByFile[v.file].push(v);
              });
              
              if (results.summary.errors > 0) {
                comment += `### 🔴 Critical Errors (Must Fix)\n\n`;
                const errors = results.violations.filter(v => v.severity === 'error');
                errors.forEach(v => {
                  comment += `- **${v.title}** in \`${v.file}\` (Line ${v.line})\n`;
                  comment += `  - ${v.description}\n`;
                  if (v.wcagCriteria && v.wcagCriteria.length > 0) {
                    comment += `  - WCAG: ${v.wcagCriteria.join(', ')}\n`;
                  }
                  comment += `  - 💡 Fix: ${v.fixSuggestion || v.help}\n\n`;
                });
              }
              
              if (results.summary.warnings > 0) {
                comment += `### 🟡 Warnings (Recommended)\n\n`;
                const warnings = results.violations.filter(v => v.severity === 'warning');
                warnings.forEach(v => {
                  comment += `- **${v.title}** in \`${v.file}\` (Line ${v.line})\n`;
                  comment += `  - ${v.description}\n`;
                  if (v.wcagCriteria && v.wcagCriteria.length > 0) {
                    comment += `  - WCAG: ${v.wcagCriteria.join(', ')}\n`;
                  }
                  comment += `  - 💡 Fix: ${v.fixSuggestion || v.help}\n\n`;
                });
              }
              
              comment += `### 📊 Summary\n\n`;
              comment += `- **Files Analyzed**: ${results.analyzedFiles}\n`;
              comment += `- **Total Violations**: ${results.summary.totalViolations}\n`;
              comment += `- **Critical Errors**: ${results.summary.errors}\n`;
              comment += `- **Warnings**: ${results.summary.warnings}\n\n`;
            }
            
            comment += `### 📚 Resources\n\n`;
            comment += `- [WCAG 2.2 Guidelines](https://www.w3.org/WAI/WCAG22/quickref/)\n`;
            comment += `- [Model Context Protocol](https://modelcontextprotocol.io/)\n`;
            comment += `- [Accessibility Testing Tools](https://github.com/dequelabs/axe-core)\n\n`;
            
            comment += `---\n`;
            comment += `*Analysis performed by A11y-MCP Server using Model Context Protocol*\n`;
            
            // Post comment to PR
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
            
            console.log('✅ Posted accessibility results to PR');

      - name: 🎯 Success Summary
        if: steps.a11y-analysis.outputs.has_errors == 'false'
        run: |
          echo "✅ Accessibility check completed successfully!"
          echo "📊 No critical errors found"
          echo "🔍 Analyzed ${{ steps.a11y-analysis.outputs.analyzedFiles }} files"
          echo "⚠️  ${{ steps.a11y-analysis.outputs.warnings }} warnings (non-blocking)"
          
          # Create summary artifact
          echo "## Accessibility Analysis Summary" > accessibility-summary.md
          echo "" >> accessibility-summary.md
          echo "**Status**: ✅ Passed" >> accessibility-summary.md
          echo "**Files Analyzed**: ${{ steps.a11y-analysis.outputs.analyzedFiles }}" >> accessibility-summary.md
          echo "**Violations Found**: ${{ steps.a11y-analysis.outputs.violations }}" >> accessibility-summary.md
          echo "**Critical Errors**: ${{ steps.a11y-analysis.outputs.errors }}" >> accessibility-summary.md
          echo "**Warnings**: ${{ steps.a11y-analysis.outputs.warnings }}" >> accessibility-summary.md
          echo "" >> accessibility-summary.md
          echo "This PR meets WCAG 2.2 AA accessibility standards." >> accessibility-summary.md

      - name: 📦 Upload Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: accessibility-analysis-results
          path: |
            a11y-results.json
            accessibility-summary.md
          retention-days: 30

      - name: ❌ Fail on Critical Errors
        if: steps.a11y-analysis.outputs.has_errors == 'true'
        run: |
          echo "❌ Accessibility check failed due to ${{ steps.a11y-analysis.outputs.errors }} critical error(s)"
          echo "🔧 Please fix the critical accessibility violations before merging"
          echo ""
          echo "Errors found:"
          cat a11y-results.json | jq -r '.violations[] | select(.severity == "error") | "- \(.title) in \(.file)"'
          exit 1